com_utils.c
CAN_TxHeaderTypeDef TxHeader
Referenced by CAN_send_msg, CAN_setup_DF.
CAN_RxHeaderTypeDef RxHeader
Referenced by HAL_CAN_RxFifo0MsgPendingCallback.
uint8_t RxData[8][8]
Referenced by HAL_CAN_RxFifo0MsgPendingCallback.
int8_t val_SEQ
int8_t val_HB
int8_t val_CI
int8_t val_AB
int8_t val_EDC
int16_t val_N2OPS
int16_t val_TLC
int8_t val_N2ODVS
int8_t val_N2OIV
int8_t val_N2OMV
int16_t val_TIME
int8_t out_Rx[8][8]
Referenced by HAL_CAN_RxFifo0MsgPendingCallback, update_TagData.
int datacheck
Referenced by HAL_CAN_RxFifo0MsgPendingCallback, update_TagData.
int8_t TxData_moteur[8][8]
int8_t RxData_moteur[8][8]
int32_t TxMailbox
Referenced by CAN_send_msg.
void init_com(void)
initialise tout les fonction de communication. (point d'appel unique: main) */
References CAN_init_TAGCAN, CAN_setup_DF, CAN_setup_TAG, hcan.
void CAN_init_TAGCAN(void)
References init_data_container, init_tag_manager.
Referenced by init_com.
void CAN_setup_DF(int32_t std_id)
References TxHeader.
Referenced by init_com.
void CAN_setup_TAG(void)
References set_tag.
Referenced by init_com.
CAN_FilterTypeDef * CAN_setup_Filter(int32_t minimum_id, int32_t maximum_id, int filterBank)
References hcan.
void main_loop(void)
References CAN_send_msg, update_all_val_send.
void update_TagData(void)
References datacheck, out_Rx.
void CAN_send_msg(void)
References hcan, TxData, TxHeader, TxMailbox.
Referenced by main_loop.
void CAN_change_val(void)
void update_val(const char *nom_du_tag, int32_t val)
References set_tag.
void update_all_val_send(void)
References set_value.
Referenced by main_loop.
void update_all_val_receve(void)
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan)
References datacheck, hcan, N_BYTES, out_Rx, RxData, RxHeader.