data_container.h
DATA_CONTAINER_H
uint8_t TxData[N_BYTES][N_BYTES]
Buffer de donnees CAN (payload de 8 octets).
Referenced by get_value, init_data_container, print_all_data_bin, print_all_with_title, set_val_TxData, set_value.
void init_data_container(void)
Reinitialise le payload TxData a zero.
Si reexecutee, la fonction efface les donnees precedemment ecrites.
References N_BYTES, TxData.
Referenced by run_all_tests, somme_other_test, test_print.
int set_value(const char *tag_name, uint32_t value)
Ecrit une valeur dans TxData a partir d'un tag.
La valeur doit tenir dans la taille du tag. En cas de depassement, l'implementation retourne CAN_TG_ERROR_VALUE_TO_BIG. tag_name Nom du tag cible. value Nouvelle valeur a ecrire. Code de succes ou code d'erreur.
References TagDef::bit_pos_a, TagDef::bit_pos_b, TagDef::byte_idx_a, TagDef::byte_idx_b, CAN_TG_ERROR_VALUE_TO_BIG, CAN_TG_SUCCESS, get_tag_def, TagDef::n_bits, prep_mask, TxData.
Referenced by run_all_tests, test_print.
int get_value(const char *tag_name, uint32_t *out_value)
Lit la valeur associee a un tag.
tag_name Nom du tag a lire. out_value Adresse de sortie qui recoit la valeur extraite. CAN_TG_SUCCESS en cas de succes, sinon un code d'erreur negatif.
References TagDef::bit_pos_a, TagDef::bit_pos_b, TagDef::byte_idx_a, TagDef::byte_idx_b, CAN_TG_ERROR_TAG_NOT_FOUND_, CAN_TG_SUCCESS, get_tag_def, TagDef::n_bits, prep_mask, TxData.
Referenced by print_all_data, run_all_tests.
uint8_t prep_mask(uint8_t p_bit, uint8_t n_bit)
[FONCTION INTERNE] Prepare un masque binaire pour set/get.
Utilise principalement pour les valeurs strictement inferieures a 8 bits. p_bit Position du premier bit (de gauche a droite). n_bit Nombre de bits de la valeur. Masque binaire aligne sur la position cible.
Referenced by get_value, set_value, somme_other_test.
void can_simulate_send_receive(uint8_t *tx_buffer, uint8_t *rx_buffer)
Simule un envoi/reception CAN par copie buffer-a-buffer.
tx_buffer Buffer source (emission). rx_buffer Buffer destination (reception). Simule un envoi/reception CAN par copie buffer-a-buffer. Copie simplement tx_buffer dans rx_buffer. tx_buffer Buffer d'emission. rx_buffer Buffer de reception.
References N_BYTES.
void set_val_TxData(uint8_t *TxDataArray)
Copie un tableau externe dans le buffer global TxData.
TxDataArray Tableau source de N_BYTES octets.
References N_BYTES, TxData.