gestion_tag.h
void init_tag_manager(void)
Initialise/reinitialise le gestionnaire de tags.
Apres cet appel, l'ensemble des tags doit etre redefini via set_tag.
References g_bytes_used, g_tag_count, g_tags, MAX_TAGS.
Referenced by CAN_init_TAGCAN, run_all_tests, somme_other_test, test_print.
int set_tag(const char *tag_name, uint8_t n_bit)
créé un nouveau tag.
tag_name le nom (id) relié a la valeur. n_bit La taille de la valeur (implémentation actuelle: 1 à 16 bits). un code de succès ou d'erreur. créé un nouveau tag. tag_name Nom logique du tag. siz Taille de la valeur en bits (implementation actuelle: 1..16). Code de succes ou code d'erreur CAN_TG_STATUE.
References CAN_TG_ERROR_NAME_ALREADY_USE, CAN_TG_ERROR_SIZE_VALUE_INVALIDE, CAN_TG_ERROR_SIZE_VALUE_INVALIDE_, CAN_TG_ERROR_TAG_NAME_INVALIDE, CAN_TG_ERROR_TAG_NAME_TO_BIGS, CAN_TG_ERROR_TOO_MAY_TAGS, CAN_TG_SUCCESS, find_byte2_with_enoung_space, find_byte_with_enoung_space, g_tag_count, general_set_tag, get_first_tags_vide, get_tag_def, MAX_TAG_NAME_LEN, MAX_TAGS, set_new_tag_9_to_16.
Referenced by CAN_setup_TAG, run_all_tests, test_print, update_val.