main.c
int passed_tests
le nombre total de test réussi
Referenced by TEST, TEST_EQ_INT, TEST_EQ_INT_.
int total_tests
le nombre total de test effectué
Referenced by TEST, TEST_EQ_INT, TEST_EQ_INT_.
void TEST(const char *name, const bool condition)
Affiche un resultat de test avec format uniforme.
name Le nom du test (peut aussi servir de description courte). condition Resultat du test (true si reussi, false sinon).
References passed_tests, total_tests.
void TEST_EQ_INT(const char *name, const int val_1, const int val_2)
Affiche un test d'egalite entre deux entiers.
name Meme usage que TEST. val_1 Premiere valeur a comparer. val_2 Deuxieme valeur a comparer.
References passed_tests, total_tests.
Referenced by run_all_tests.
void test_print(void)
Execute un scenario de demonstration des fonctions d'impression.
Initialise des tags/valeurs puis affiche metadonnees et repartition.
References init_data_container, init_tag_manager, print_all_data, print_all_tag_set, print_repartition_bit, set_tag, set_value.
Referenced by main.
void somme_other_test(void)
Scenario de test manuel des operations de masque/shift.
References init_data_container, init_tag_manager, prep_mask, print_bin_8.
void run_all_tests(void)
Execute les tests unitaires du module. Les resultats sont affiches dans le terminal.
References CAN_TG_ERROR_NAME_ALREADY_USE, CAN_TG_ERROR_NOT_ENOUNG_SPACE, CAN_TG_ERROR_SIZE_VALUE_INVALIDE, CAN_TG_SUCCESS, get_value, init_data_container, init_tag_manager, set_tag, set_value, SUCCES, SUCCES_TO_SET, TEST_EQ_INT.
Referenced by main.
int main(void)
References run_all_tests, test_print.