print_val.h
tsfp gbc2[9][9]
Espace global de rendu utilise par les fonctions d'impression de repartition.
void print_bin_8(uint8_t val)
Affiche la representation binaire (8 bits) d'une valeur.
val Valeur a afficher en binaire sur 8 bits. Affiche la representation binaire (8 bits) d'une valeur. val The val [from 0 to 255]. The function prints the binary representation of this value by iterating over each bit.
Referenced by print_all_data_bin, print_all_with_title, somme_other_test.
void print_all_data_bin(void)
Affiche tout le payload TxData en binaire.
Chaque octet est affiche sur 8 bits, dans l'ordre du buffer. Affiche tout le payload TxData en binaire. Prints the binary representation of each byte in the TxData array.
References N_BYTES, print_bin_8, TxData.
void print_all_with_title(const char *title)
Affiche TxData en binaire avec un titre en prefixe.
title Texte affiche avant la ligne binaire. Affiche TxData en binaire avec un titre en prefixe. title Libelle affiche avant les octets.
References N_BYTES, print_bin_8, TxData.
void print_all_tag_set(void)
Affiche la table des tags declares et leurs metadonnees.
Affiche la table des tags declares et leurs metadonnees.
References g_tag_count, g_tags.
Referenced by test_print.
void print_all_data(void)
Affiche toutes les valeurs logiques relues via get_value.
Affiche toutes les valeurs logiques relues via get_value. Chaque valeur est relue via get_value puis imprimee.
References g_tag_count, g_tags, get_value.
Referenced by test_print.
void print_repartition_bit(void)
Affiche la repartition des bits utilises dans la trame CAN.
Affiche la repartition des bits utilises dans la trame CAN.
References g_tag_count, g_tags, N_BYTES.
Referenced by test_print.