print_val.c
tsfp gbc2[9][9]
Espace global de rendu utilise par les fonctions d'impression de repartition.
Referenced by print_repartition_bit.
void print_all_tag_set(void)
Affiche la liste complete des tags et leurs metadonnees.
Affiche la table des tags declares et leurs metadonnees.
References g_tag_count, g_tags.
Referenced by test_print.
void print_all_data(void)
Affiche toutes les valeurs logiques des tags.
Affiche toutes les valeurs logiques relues via get_value. Chaque valeur est relue via get_value puis imprimee.
References g_tag_count, g_tags, get_value.
Referenced by test_print.
void modif_vt(int8_t bia, int8_t bib, uint8_t bpa, uint8_t bpb, uint8_t nb, char *v1, char *v2, char *v3, char *v4, char *v5, char *v6, char *v7, char *v8)
Affiche la repartition des tags dans les bytes de la trame CAN.
[INTERNE] Point d'extension pour la construction de vues de repartition. Fonction actuellement inachevee/conservee pour evolution future.
void print_repartition_bit(void)
Affiche une vue textuelle de l'occupation des bits de la trame.
Affiche la repartition des bits utilises dans la trame CAN.
References g_tag_count, g_tags, gbc2, N_BYTES.
Referenced by test_print.
void print_bin_8(uint8_t val)
Prints the binary representation of an 8-bit unsigned integer.
Affiche la representation binaire (8 bits) d'une valeur. val The val [from 0 to 255]. The function prints the binary representation of this value by iterating over each bit.
Referenced by print_all_data_bin, print_all_with_title, somme_other_test.
void print_all_data_bin(void)
Prints the binary representation of each byte in TxData.
Affiche tout le payload TxData en binaire. Prints the binary representation of each byte in the TxData array.
References N_BYTES, print_bin_8, TxData.
void print_all_with_title(const char *title)
Affiche TxData en binaire avec un titre.
Affiche TxData en binaire avec un titre en prefixe. title Libelle affiche avant les octets.
References N_BYTES, print_bin_8, TxData.