tag_manager.c
TagDef g_tags[MAX_TAGS][MAX_TAGS]
Table des tags (actifs et inactifs).
Referenced by general_set_tag, get_first_tags_vide, get_tag_def, init_tag_manager, print_all_data, print_all_tag_set, print_repartition_bit, set_name_tag, set_new_tag_9_to_16.
uint8_t g_tag_count
Nombre de tags actifs (max: MAX_TAGS).
Referenced by general_set_tag, get_tag_def, init_tag_manager, print_all_data, print_all_tag_set, print_repartition_bit, set_tag.
uint8_t g_bytes_used[N_BYTES][N_BYTES]
Occupation courante en bits pour chaque byte du payload.
Referenced by find_byte2_with_enoung_space, find_byte_with_enoung_space, general_set_tag, init_tag_manager, set_new_tag_9_to_16.
void init_tag_manager(void)
Initialise/reinitialise le gestionnaire de tags.
Apres cet appel, l'ensemble des tags doit etre redefini via set_tag.
References g_bytes_used, g_tag_count, g_tags, MAX_TAGS.
Referenced by CAN_init_TAGCAN, run_all_tests, somme_other_test, test_print.
int get_first_tags_vide(void)
[INTERNE] Retourne l'index du premier slot tag libre.
Un slot est considere libre si son nom est NULL ou vide ('\0'). Index du slot libre, ou CAN_TG_ERROR_TOO_MAY_TAGS si aucun slot disponible.
References CAN_TG_ERROR_TOO_MAY_TAGS, g_tags, MAX_TAGS.
Referenced by set_new_tag_9_to_16, set_tag.
void set_name_tag(const int n_tag, const char *tag_name)
[INTERNE] Enregistre un nom de tag dans un slot.
Les verifications d'entree sont censees etre faites en amont. n_tag Index du slot (0..MAX_TAGS-1). tag_name Nom logique du tag.
References g_tags, MAX_TAG_NAME_LEN.
Referenced by general_set_tag.
void general_set_tag(const int n_tag, const char *tag_name, uint8_t n_bits, int8_t byte_idx_a)
[INTERNE] Initialise les champs communs d'un tag.
n_tag Index du slot tag cible. tag_name Nom logique a enregistrer. n_bits Taille de la valeur en bits. byte_idx_a Byte principal de stockage (partie A).
References g_bytes_used, g_tag_count, g_tags, set_name_tag.
Referenced by set_new_tag_9_to_16, set_tag.
void set_new_tag_9_to_16(const char *tag_name, const int8_t byte_idx_a, const int8_t byte_idx_b, uint8_t n_bits_total)
[INTERNE] Cree un tag avec repartition potentielle sur 2 bytes.
tag_name Nom logique du tag. byte_idx_a Byte de la partie A. byte_idx_b Byte de la partie B. n_bits_total Taille totale en bits.
References g_bytes_used, g_tags, general_set_tag, get_first_tags_vide.
Referenced by set_tag.
CAN_TG_STATUE find_byte_with_enoung_space(uint8_t siz, int8_t *retur_var)
Trouve le premier byte ayant assez de place libre.
siz Taille demandee (en bits). retur_var Sortie: index du byte selectionne. CAN_TG_SUCCESS ou CAN_TG_ERROR_NOT_ENOUNG_SPACE_.
References CAN_TG_ERROR_NOT_ENOUNG_SPACE_, CAN_TG_SUCCESS, g_bytes_used, N_BYTES.
Referenced by set_tag.
CAN_TG_STATUE find_byte2_with_enoung_space(uint8_t siz_total, int8_t posi_premier_bit, int8_t *retur_var)
Variante de recherche en excluant le byte deja utilise par la partie A.
siz_total Taille totale (9..16). posi_premier_bit Byte deja retenu pour la partie A. retur_var Sortie: index du byte pour la partie B. CAN_TG_SUCCESS ou CAN_TG_ERROR_NOT_ENOUNG_SPACE_.
References CAN_TG_ERROR_NOT_ENOUNG_SPACE_, CAN_TG_SUCCESS, g_bytes_used, N_BYTES.
Referenced by set_tag.
CAN_TG_STATUE set_tag(const char *tag_name, uint8_t siz)
Declare un nouveau tag et reserve son espace dans TxData.
créé un nouveau tag. tag_name Nom logique du tag. siz Taille de la valeur en bits (implementation actuelle: 1..16). Code de succes ou code d'erreur CAN_TG_STATUE.
References CAN_TG_ERROR_NAME_ALREADY_USE, CAN_TG_ERROR_SIZE_VALUE_INVALIDE, CAN_TG_ERROR_SIZE_VALUE_INVALIDE_, CAN_TG_ERROR_TAG_NAME_INVALIDE, CAN_TG_ERROR_TAG_NAME_TO_BIGS, CAN_TG_ERROR_TOO_MAY_TAGS, CAN_TG_SUCCESS, find_byte2_with_enoung_space, find_byte_with_enoung_space, g_tag_count, general_set_tag, get_first_tags_vide, get_tag_def, MAX_TAG_NAME_LEN, MAX_TAGS, set_new_tag_9_to_16.
Referenced by CAN_setup_TAG, run_all_tests, test_print, update_val.
const TagDef * get_tag_def(const char *tag_name)
Recherche un tag actif par son nom.
Recherche un tag et retourne sa definition. tag_name Nom du tag recherche. Pointeur sur TagDef si trouve, sinon NULL.
References g_tag_count, g_tags, MAX_TAG_NAME_LEN.
Referenced by get_value, set_tag, set_value.