.TH "Répertoire de référence de scripts" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de scripts
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBsub_scripts\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBconfig_value\&.c\fP"
.br
.ti -1c
.RI "fichier \fBmain\&.c\fP"
.br
.ti -1c
.RI "fichier \fBmain_func\&.c\fP"
.br
.in -1c
