.TH "scripts Directory Reference" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsub_scripts\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCAN_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBconfig_value\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
