.TH "sub_scripts Directory Reference" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sub_scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdata_container\&.c\fP"
.br
.ti -1c
.RI "file \fBprint_val\&.c\fP"
.br
.ti -1c
.RI "file \fBtag_manager\&.c\fP"
.br
.in -1c
