.TH "Répertoire de référence de sub_scripts" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de sub_scripts
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBdata_container\&.c\fP"
.br
.ti -1c
.RI "fichier \fBprint_val\&.c\fP"
.br
.ti -1c
.RI "fichier \fBtag_manager\&.c\fP"
.br
.in -1c
