.TH "config_value.c" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_value.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/config_value\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBCAN_TG_ERROR_NOT_ENOUNG_SPACE\fP = \-2"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_TAG_NOT_FOUND\fP = \-3"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_TAG_NAME_TO_BIGS\fP = \-4"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_TOO_MAY_TAGS\fP = \-5"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_SIZE_VALUE_INVALIDE\fP = \-6"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_NAME_ALREADY_USE\fP = \-7"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_SUBDIVISION_FAIL\fP = \-8"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_TAG_NAME_INVALIDE\fP =\-9"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_NULL_POINTOR\fP = \-20"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_TRY_TO_FIND_END_CARACTER\fP = \-21"
.br
.ti -1c
.RI "const int \fBCAN_TG_ERROR_INTERNAL_CORUPTION\fP = \-30"
.br
.ti -1c
.RI "const int \fBSUCCES_TO_SET\fP = 1"
.br
.ti -1c
.RI "const int \fBSUCCES\fP = 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int CAN_TG_ERROR_INTERNAL_CORUPTION = \-30"
Code d'erreur: corruption interne detectee\&. 
.PP
Definition at line \fB15\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_NAME_ALREADY_USE = \-7"
Code d'erreur: nom de tag deja utilise\&. 
.PP
Definition at line \fB10\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_NOT_ENOUNG_SPACE = \-2"
Code d'erreur: espace memoire insuffisant\&. 
.PP
Definition at line \fB5\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_NULL_POINTOR = \-20"
Code d'erreur: pointeur NULL recu\&. 
.PP
Definition at line \fB13\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_SIZE_VALUE_INVALIDE = \-6"
Code d'erreur: taille de valeur invalide\&. 
.PP
Definition at line \fB9\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_SUBDIVISION_FAIL = \-8"
Code d'erreur: echec de subdivision/allocation\&. 
.PP
Definition at line \fB11\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_TAG_NAME_INVALIDE =\-9"
Code d'erreur: nom de tag invalide\&. 
.PP
Definition at line \fB12\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_TAG_NAME_TO_BIGS = \-4"
Code d'erreur: nom de tag trop long\&. 
.PP
Definition at line \fB7\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_TAG_NOT_FOUND = \-3"
Code d'erreur: tag introuvable\&. 
.PP
Definition at line \fB6\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_TOO_MAY_TAGS = \-5"
Code d'erreur: trop de tags declares\&. 
.PP
Definition at line \fB8\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int CAN_TG_ERROR_TRY_TO_FIND_END_CARACTER = \-21"
Code d'erreur: fin de chaine non trouvee\&. 
.PP
Definition at line \fB14\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int SUCCES = 1"
Code de succes generique historique\&. 
.PP
Definition at line \fB17\fP of file \fBconfig_value\&.c\fP\&.
.SS "const int SUCCES_TO_SET = 1"
Code de succes historique pour set_tag/set_value\&. 
.PP
Definition at line \fB16\fP of file \fBconfig_value\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TAGCAN from the source code\&.
