.TH "data_container.h" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_container.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'tag_manager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_data_container\fP (void)"
.br
.RI "Reinitialise le payload TxData a zero\&. "
.ti -1c
.RI "int \fBset_value\fP (const char *tag_name, uint32_t value)"
.br
.RI "Ecrit une valeur dans TxData a partir d'un tag\&. "
.ti -1c
.RI "int \fBget_value\fP (const char *tag_name, uint32_t *out_value)"
.br
.RI "Lit la valeur associee a un tag\&. "
.ti -1c
.RI "uint8_t \fBprep_mask\fP (uint8_t p_bit, uint8_t n_bit)"
.br
.RI "[FONCTION INTERNE] Prepare un masque binaire pour set/get\&. "
.ti -1c
.RI "void \fBcan_simulate_send_receive\fP (uint8_t *tx_buffer, uint8_t *rx_buffer)"
.br
.RI "Simule un envoi/reception CAN par copie buffer-a-buffer\&. "
.ti -1c
.RI "void \fBset_val_TxData\fP (uint8_t *TxDataArray)"
.br
.RI "Copie un tableau externe dans le buffer global TxData\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t \fBTxData\fP [\fBN_BYTES\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void can_simulate_send_receive (uint8_t * tx_buffer, uint8_t * rx_buffer)"

.PP
Simule un envoi/reception CAN par copie buffer-a-buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fItx_buffer\fP Buffer source (emission)\&. 
.br
\fIrx_buffer\fP Buffer destination (reception)\&.
.RE
.PP
Simule un envoi/reception CAN par copie buffer-a-buffer\&.

.PP
Copie simplement tx_buffer dans rx_buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fItx_buffer\fP Buffer d'emission\&. 
.br
\fIrx_buffer\fP Buffer de reception\&. 
.RE
.PP

.PP
Definition at line \fB165\fP of file \fBdata_container\&.c\fP\&.
.SS "int get_value (const char * tag_name, uint32_t * out_value)"

.PP
Lit la valeur associee a un tag\&. 
.PP
\fBParameters\fP
.RS 4
\fItag_name\fP Nom du tag a lire\&. 
.br
\fIout_value\fP Adresse de sortie qui recoit la valeur extraite\&. 
.RE
.PP
\fBReturns\fP
.RS 4
CAN_TG_SUCCESS en cas de succes, sinon un code d'erreur negatif\&. 
.RE
.PP
Copie un buffer externe dans TxData\&. 
.PP
\fBParameters\fP
.RS 4
\fITxDataArray\fP Tableau source de N_BYTES octets\&.
.RE
.PP
Recompose un entier 16 bits depuis deux octets\&. 
.PP
\fBParameters\fP
.RS 4
\fIba\fP Octet de poids faible\&. 
.br
\fIbb\fP Octet de poids fort\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Valeur 16 bits combinee\&.
.RE
.PP

.PP
Definition at line \fB106\fP of file \fBdata_container\&.c\fP\&.
.SS "void init_data_container (void )"

.PP
Reinitialise le payload TxData a zero\&. Si reexecutee, la fonction efface les donnees precedemment ecrites\&. 
.PP
Definition at line \fB14\fP of file \fBdata_container\&.c\fP\&.
.SS "uint8_t prep_mask (uint8_t p_bit, uint8_t n_bit)"

.PP
[FONCTION INTERNE] Prepare un masque binaire pour set/get\&. Utilise principalement pour les valeurs strictement inferieures a 8 bits\&. 
.PP
\fBParameters\fP
.RS 4
\fIp_bit\fP Position du premier bit (de gauche a droite)\&. 
.br
\fIn_bit\fP Nombre de bits de la valeur\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Masque binaire aligne sur la position cible\&. 
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBdata_container\&.c\fP\&.
.SS "void set_val_TxData (uint8_t * TxDataArray)"

.PP
Copie un tableau externe dans le buffer global TxData\&. 
.PP
\fBParameters\fP
.RS 4
\fITxDataArray\fP Tableau source de N_BYTES octets\&. 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBdata_container\&.c\fP\&.
.SS "int set_value (const char * tag_name, uint32_t value)"

.PP
Ecrit une valeur dans TxData a partir d'un tag\&. 
.PP
\fBWarning\fP
.RS 4
La valeur doit tenir dans la taille du tag\&.
.RE
.PP
En cas de depassement, l'implementation retourne CAN_TG_ERROR_VALUE_TO_BIG\&. 
.PP
\fBParameters\fP
.RS 4
\fItag_name\fP Nom du tag cible\&. 
.br
\fIvalue\fP Nouvelle valeur a ecrire\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code de succes ou code d'erreur\&. 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBdata_container\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t TxData[\fBN_BYTES\fP]\fR [extern]\fP"
Buffer de donnees CAN (payload de 8 octets)\&. 
.PP
Definition at line \fB12\fP of file \fBdata_container\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TAGCAN from the source code\&.
