.TH "gestion_tag.h" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gestion_tag.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_tag_manager\fP (void)"
.br
.RI "Initialise/reinitialise le gestionnaire de tags\&. "
.ti -1c
.RI "int \fBset_tag\fP (const char *tag_name, uint8_t n_bit)"
.br
.RI "créé un nouveau tag\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_tag_manager (void )"

.PP
Initialise/reinitialise le gestionnaire de tags\&. 
.PP
\fBNote\fP
.RS 4
Apres cet appel, l'ensemble des tags doit etre redefini via \fR\fBset_tag\fP\fP\&. 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBtag_manager\&.c\fP\&.
.SS "int set_tag (const char * tag_name, uint8_t siz)"

.PP
créé un nouveau tag\&. 
.PP
\fBParameters\fP
.RS 4
\fItag_name\fP le nom (id) relié a la valeur\&. 
.br
\fIn_bit\fP La taille de la valeur (implémentation actuelle: 1 à 16 bits)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
un code de succès ou d'erreur\&.
.RE
.PP
créé un nouveau tag\&.

.PP
\fBParameters\fP
.RS 4
\fItag_name\fP Nom logique du tag\&. 
.br
\fIsiz\fP Taille de la valeur en bits (implementation actuelle: 1\&.\&.16)\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code de succes ou code d'erreur \fBCAN_TG_STATUE\fP\&. 
.RE
.PP

.PP
Definition at line \fB232\fP of file \fBtag_manager\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TAGCAN from the source code\&.
