.TH "main_func.c" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_func.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/sub_include/data_container\&.h'\fP
.br
\fR#include '\&.\&./include/sub_include/tag_manager\&.h'\fP
.br
\fR#include '\&.\&./include/config_value\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour TAGCAN à partir du code source\&.
