.TH "print_val.c" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
print_val.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./include/sub_include/print_val\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./include/sub_include/tag_manager\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./include/sub_include/data_container\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBprint_all_tag_set\fP (void)"
.br
.ti -1c
.RI "void \fBprint_all_data\fP (void)"
.br
.ti -1c
.RI "void \fBmodif_vt\fP (int8_t bia, int8_t bib, uint8_t bpa, uint8_t bpb, uint8_t nb, char *v1, char *v2, char *v3, char *v4, char *v5, char *v6, char *v7, char *v8)"
.br
.RI "print in the terminal the place where the module place the value in the bytes of the CAN frame\&. "
.ti -1c
.RI "void \fBprint_repartition_bit\fP (void)"
.br
.ti -1c
.RI "void \fBprint_bin_8\fP (uint8_t val)"
.br
.RI "imprime dans le terminal la représentation 8 bits (binaire) de la valeur passé en argument "
.ti -1c
.RI "void \fBprint_all_data_bin\fP (void)"
.br
.ti -1c
.RI "void \fBprint_all_with_title\fP (const char *title)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtsfp\fP \fBgbc2\fP [9]"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void modif_vt (int8_t bia, int8_t bib, uint8_t bpa, uint8_t bpb, uint8_t nb, char * v1, char * v2, char * v3, char * v4, char * v5, char * v6, char * v7, char * v8)"

.PP
print in the terminal the place where the module place the value in the bytes of the CAN frame\&. 
.SS "void print_all_data (void )"

.SS "void print_all_data_bin (void )"
prints the binary representation of each byte in the \fR\fBTxData\fP\fP array\&. 
.SS "void print_all_tag_set (void )"

.SS "void print_all_with_title (const char * title)"

.SS "void print_bin_8 (uint8_t val)"

.PP
imprime dans le terminal la représentation 8 bits (binaire) de la valeur passé en argument @bref prints the binary representation of an 8-bit unsigned integer\&.

.PP
\fBParamètres\fP
.RS 4
\fIval\fP The \fRval\fP [from 0 to 255]\&. The function prints the binary representation of this value by iterating over each bit\&. 
.RE
.PP

.SS "void print_repartition_bit (void )"

.SH "Documentation des variables"
.PP 
.SS "\fBtsfp\fP gbc2[9]"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour TAGCAN à partir du code source\&.
