.TH "tag_manager.h" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tag_manager.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./config_value\&.h'\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTagDef\fP"
.br
.RI "Structure de definition d'un tag\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBTagDef\fP * \fBget_tag_def\fP (const char *tag_name)"
.br
.RI "Recherche un tag et retourne sa definition\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTagDef\fP \fBg_tags\fP [\fBMAX_TAGS\fP]"
.br
.ti -1c
.RI "uint8_t \fBg_tag_count\fP"
.br
.ti -1c
.RI "uint8_t \fBg_bytes_used\fP [\fBN_BYTES\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBTagDef\fP * get_tag_def (const char * tag_name)"

.PP
Recherche un tag et retourne sa definition\&. 
.PP
\fBWarning\fP
.RS 4
API surtout utilisee en interne par le module de valeurs\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fItag_name\fP Nom du tag a chercher\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointeur vers le tag si trouve, sinon NULL\&.
.RE
.PP
Recherche un tag et retourne sa definition\&.

.PP
\fBParameters\fP
.RS 4
\fItag_name\fP Nom du tag recherche\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Pointeur sur \fBTagDef\fP si trouve, sinon NULL\&. 
.RE
.PP

.PP
Definition at line \fB288\fP of file \fBtag_manager\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t g_bytes_used[\fBN_BYTES\fP]\fR [extern]\fP"
Occupation courante en bits pour chaque byte du payload\&. 
.PP
Definition at line \fB19\fP of file \fBtag_manager\&.c\fP\&.
.SS "uint8_t g_tag_count\fR [extern]\fP"
Nombre de tags actifs (max: MAX_TAGS)\&. 
.PP
Definition at line \fB18\fP of file \fBtag_manager\&.c\fP\&.
.SS "\fBTagDef\fP g_tags[\fBMAX_TAGS\fP]\fR [extern]\fP"
Table des tags (actifs et inactifs)\&. 
.PP
Definition at line \fB17\fP of file \fBtag_manager\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TAGCAN from the source code\&.
