.TH "TAGCAN_fonction.h" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAGCAN_fonction.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sub_include/data_container\&.h'\fP
.br
\fR#include 'sub_include/tag_manager\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour TAGCAN à partir du code source\&.
