.TH "TAGCAN.h" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAGCAN.h
.SH SYNOPSIS
.br
.PP
\fR#include 'include/config_value\&.h'\fP
.br
\fR#include 'include/gestion_tag\&.h'\fP
.br
\fR#include 'include/sub_include/data_container\&.h'\fP
.br
\fR#include 'include/sub_include/tag_manager\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for TAGCAN from the source code\&.
