.TH "test_print_repartition_bit.c" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_print_repartition_bit.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include '\&.\&./\&.\&./include/gestion_tag\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./include/sub_include/data_container\&.h'\fP
.br
\fR#include '\&.\&./\&.\&./include/sub_include/print_val\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain__\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main__ (void )"

.PP
Definition at line \fB79\fP of file \fBtest_print_repartition_bit\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TAGCAN from the source code\&.
