.TH "tsfp" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsfp \- Buffer de rendu pour l'affichage de repartition bit-a-bit\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <print_val\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBbi\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Buffer de rendu pour l'affichage de repartition bit-a-bit\&. 
.PP
Definition at line \fB39\fP of file \fBprint_val\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char bi[8]"

.PP
Definition at line \fB40\fP of file \fBprint_val\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TAGCAN from the source code\&.
