.TH "tsfp" 3 "TAGCAN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsfp
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <print_val\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "char \fBbi\fP [8]"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "char bi[8]"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour TAGCAN à partir du code source\&.
