var searchData=
[
  ['d_20ensemble_0',['Vue d&apos;ensemble',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md1',1,'']]],
  ['data_5fcontainer_2ec_1',['data_container.c',['../data__container_8c.html',1,'']]],
  ['data_5fcontainer_2eh_2',['data_container.h',['../data__container_8h.html',1,'']]],
  ['data_5fcontainer_5fh_3',['DATA_CONTAINER_H',['../data__container_8h.html#ab1e0c45daf869a5ff0a8c836629d657f',1,'data_container.h']]],
  ['de_20coherence_4',['Verification de coherence',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html',1,'']]],
  ['de_20comportement_5',['Notes importantes de comportement',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md13',1,'']]],
  ['de_20remediation_6',['Priorites de remediation',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html#autotoc_md22',1,'']]],
  ['de_20retour_7',['Codes de retour',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md10',1,'']]],
  ['de_20retour_20coherent_20en_20surface_20mais_20code_20divergent_8',['4) Commentaire de retour coherent en surface mais code divergent',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md29',1,'']]],
  ['de_20specificateurs_20printf_9',['6) Probleme de specificateurs &lt;span class=&quot;tt&quot;&gt;printf&lt;/span&gt;',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md31',1,'']]],
  ['de_20taille_20documentee_20vs_20code_20reel_10',['2) Contrainte de taille documentee vs code reel',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md27',1,'']]],
  ['debug_20affichage_11',['Debug / affichage',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md9',1,'']]],
  ['debug_20partiellement_20invalide_12',['5) Documentation debug partiellement invalide',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md30',1,'']]],
  ['des_20commentaires_13',['Audit des commentaires',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html',1,'']]],
  ['des_20tags_14',['Gestion des tags',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md7',1,'']]],
  ['divergent_15',['4) Commentaire de retour coherent en surface mais code divergent',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md29',1,'']]],
  ['documentation_20creee_20vs_20code_16',['Axe C - Documentation creee vs code',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html#autotoc_md19',1,'']]],
  ['documentation_20debug_20partiellement_20invalide_17',['5) Documentation debug partiellement invalide',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md30',1,'']]],
  ['documentation_20tagcan_18',['Documentation TAGCAN',['../dir_138aff360eb965c43b94267b8d1ce09e.html#autotoc_md35',1,'']]],
  ['documentation_2freadme_2emd_19',['README.md',['../documentation_2_r_e_a_d_m_e_8md.html',1,'']]],
  ['documentee_20vs_20code_20reel_20',['2) Contrainte de taille documentee vs code reel',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md27',1,'']]],
  ['doxygen_20incomplets_20mal_20formes_21',['3) Parametres Doxygen incomplets/mal formes',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md28',1,'']]],
  ['duplique_22',['1) Header duplique et commentaire duplique',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md26',1,'']]],
  ['duplique_20et_20commentaire_20duplique_23',['1) Header duplique et commentaire duplique',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md26',1,'']]]
];
