var searchData=
[
  ['c_0',['Constantes globales (&lt;span class=&quot;tt&quot;&gt;scripts/config_value.c&lt;/span&gt;)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md12',1,'']]],
  ['c_20documentation_20creee_20vs_20code_1',['Axe C - Documentation creee vs code',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html#autotoc_md19',1,'']]],
  ['can_5ftg_5fstatue_20include_20config_5fvalue_20h_2',['Enum &lt;span class=&quot;tt&quot;&gt;CAN_TG_STATUE&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;include/config_value.h&lt;/span&gt;)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md11',1,'']]],
  ['code_3',['Axe C - Documentation creee vs code',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html#autotoc_md19',1,'']]],
  ['code_20divergent_4',['4) Commentaire de retour coherent en surface mais code divergent',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md29',1,'']]],
  ['code_20reel_5',['2) Contrainte de taille documentee vs code reel',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md27',1,'']]],
  ['codes_20de_20retour_6',['Codes de retour',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md10',1,'']]],
  ['coherence_7',['Verification de coherence',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html',1,'']]],
  ['coherent_20en_20surface_20mais_20code_20divergent_8',['4) Commentaire de retour coherent en surface mais code divergent',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md29',1,'']]],
  ['commentaire_20de_20retour_20coherent_20en_20surface_20mais_20code_20divergent_9',['4) Commentaire de retour coherent en surface mais code divergent',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md29',1,'']]],
  ['commentaire_20duplique_10',['1) Header duplique et commentaire duplique',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md26',1,'']]],
  ['commentaires_11',['Audit des commentaires',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html',1,'']]],
  ['commentaires_20vs_20implementation_12',['Axe A - Commentaires vs implementation',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html#autotoc_md17',1,'']]],
  ['comportement_13',['Notes importantes de comportement',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md13',1,'']]],
  ['conclusion_14',['Conclusion',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html#autotoc_md21',1,'']]],
  ['config_5fvalue_20c_15',['Constantes globales (&lt;span class=&quot;tt&quot;&gt;scripts/config_value.c&lt;/span&gt;)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md12',1,'']]],
  ['config_5fvalue_20h_16',['Enum &lt;span class=&quot;tt&quot;&gt;CAN_TG_STATUE&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;include/config_value.h&lt;/span&gt;)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md11',1,'']]],
  ['constantes_20globales_20scripts_20config_5fvalue_20c_17',['Constantes globales (&lt;span class=&quot;tt&quot;&gt;scripts/config_value.c&lt;/span&gt;)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md12',1,'']]],
  ['contenu_18',['Contenu',['../dir_138aff360eb965c43b94267b8d1ce09e.html#autotoc_md36',1,'']]],
  ['contrainte_20de_20taille_20documentee_20vs_20code_20reel_19',['2) Contrainte de taille documentee vs code reel',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_m_m_e_n_t_a_i_r_e_s___a_u_d_i_t.html#autotoc_md27',1,'']]],
  ['creee_20vs_20code_20',['Axe C - Documentation creee vs code',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_c_o_h_e_r_e_n_c_e.html#autotoc_md19',1,'']]]
];
