var searchData=
[
  ['réception_0',['Workflow complet : Écriture -&amp;gt; Envoi -&amp;gt; Réception',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_203___d_o_n_n_e_e_s___c_a_n.html#autotoc_md80',1,'']]],
  ['réception_1',['Code de réception',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_203___d_o_n_n_e_e_s___c_a_n.html#autotoc_md84',1,'']]],
  ['réception_20rx_2',['Réception (Rx)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_203___d_o_n_n_e_e_s___c_a_n.html#autotoc_md83',1,'']]],
  ['réception_20traitement_3',['Exemple : Envoi -&amp;gt; Réception -&amp;gt; Traitement',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_203___d_o_n_n_e_e_s___c_a_n.html#autotoc_md94',1,'']]],
  ['référence_4',['Documentation de référence',['../dir_7a7edcf529884078f481081b33ab25c5.html#autotoc_md160',1,'']]],
  ['réinitialiseras_20les_20valeurs_20à_200_5',['- Atention: un appel en cours d&apos;exécution réinitialiseras les valeurs à 0.',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_201___i_n_i_t_i_a_l_i_s_a_t_i_o_n.html#autotoc_md22',1,'']]],
  ['réponse_6',['Exemple 2 : Système de commande avec réponse',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_205___e286b88c2636fb4118cac9c95749c8f33.html#autotoc_md141',1,'']]],
  ['rapide_7',['Démarrage rapide',['../dir_7a7edcf529884078f481081b33ab25c5.html#autotoc_md159',1,'']]],
  ['recommandé_8',['Stratégie 1 : Filtrage par catégorie (Recommandé)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_204___f_i_l_t_r_a_g_e___c_a_n.html#autotoc_md122',1,'']]],
  ['recommandé_9',['recommandé',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_204___f_i_l_t_r_a_g_e___c_a_n.html#autotoc_md132',1,'Avec filtres (recommandé)'],['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_202___g_e_s_t_i_o_n___t_a_g_s.html#autotoc_md64',1,'Schéma de tags recommandé']]],
  ['recommandées_10',['Stratégies de filtrage recommandées',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_204___f_i_l_t_r_a_g_e___c_a_n.html#autotoc_md121',1,'']]],
  ['reference_20etat_20actuel_11',['API Reference (Etat actuel)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html',1,'']]],
  ['retour_12',['retour',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2documentation_2_a_p_i___r_e_f_e_r_e_n_c_e.html#autotoc_md10',1,'Codes de retour'],['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_202___g_e_s_t_i_o_n___t_a_g_s.html#autotoc_md43',1,'Valeur de retour'],['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_202___g_e_s_t_i_o_n___t_a_g_s.html#autotoc_md49',1,'Valeur de retour'],['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_202___g_e_s_t_i_o_n___t_a_g_s.html#autotoc_md56',1,'Valeur de retour'],['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_204___f_i_l_t_r_a_g_e___c_a_n.html#autotoc_md104',1,'Valeur de retour']]],
  ['rx_13',['Réception (Rx)',['../md__c_1_2programation_2ulaval_2_g_a_u_l_2programmation_2_t_a_g_c_a_n_2guide__utilisation_203___d_o_n_n_e_e_s___c_a_n.html#autotoc_md83',1,'']]]
];
